<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: version1.proto

namespace Version1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>version1.Favorites</code>
 */
class Favorites extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 count = 1;</code>
     */
    protected $count = 0;
    /**
     * Generated from protobuf field <code>repeated .version1.Favorites.Movie movies = 2;</code>
     */
    private $movies;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $count
     *     @type \Version1\Favorites\Movie[]|\Google\Protobuf\Internal\RepeatedField $movies
     * }
     */
    public function __construct($data = NULL) {
        \Version1\Metadata\Version1::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 count = 1;</code>
     * @return int
     */
    public function getCount()
    {
        return $this->count;
    }

    /**
     * Generated from protobuf field <code>int32 count = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .version1.Favorites.Movie movies = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMovies()
    {
        return $this->movies;
    }

    /**
     * Generated from protobuf field <code>repeated .version1.Favorites.Movie movies = 2;</code>
     * @param \Version1\Favorites\Movie[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMovies($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Version1\Favorites\Movie::class);
        $this->movies = $arr;

        return $this;
    }

}

