<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: version1.proto

namespace Version1;

if (false) {
    /**
     * This class is deprecated. Use Version1\Favorites\Movie\Genre instead.
     * @deprecated
     */
    class Favorites_Movie_Genre {}
}
class_exists(Favorites\Movie\Genre::class);
@trigger_error('Version1\Favorites_Movie_Genre is deprecated and will be removed in the next major release. Use Version1\Favorites\Movie\Genre instead', E_USER_DEPRECATED);

