<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: version1.proto

namespace Version1;

if (false) {
    /**
     * This class is deprecated. Use Version1\Favorites\Movie instead.
     * @deprecated
     */
    class Favorites_Movie {}
}
class_exists(Favorites\Movie::class);
@trigger_error('Version1\Favorites_Movie is deprecated and will be removed in the next major release. Use Version1\Favorites\Movie instead', E_USER_DEPRECATED);

