<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: version1.proto

namespace Version1;

if (false) {
    /**
     * This class is deprecated. Use Version1\Request\State instead.
     * @deprecated
     */
    class Request_State {}
}
class_exists(Request\State::class);
@trigger_error('Version1\Request_State is deprecated and will be removed in the next major release. Use Version1\Request\State instead', E_USER_DEPRECATED);

