<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: version1.proto

namespace Version1;

/**
 * Protobuf type <code>version1.SearchService</code>
 */
interface SearchServiceInterface
{
    /**
     * Method <code>searchFav</code>
     *
     * @param \Version1\Request $request
     * @return \Version1\Favorites
     */
    public function searchFav(\Version1\Request $request);

}

